version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: app:Dockerfile
        container_name: difa_app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./php.ini:/usr/local/etc/php/php.ini
        networks:
            - difa_network
        depends_on:
            - db

    nginx:
        build:
            context: .
            dockerfile: Dockerfile.nginx
        image: nginx:Dockerfile
        container_name: difa_nginx
        restart: unless-stopped
        ports:
            - "80:80"
#        volumes:
#            - .:/var/www
#            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - difa_network

    adminer:
        image: adminer
        ports:
            - '8080:8080'
        container_name: difa_adminer
        networks:
            - difa_network
        depends_on:
            - db

    db:
        image: postgres:15.3
        container_name: difa_postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: difa
            POSTGRES_USER: difa
            POSTGRES_PASSWORD: difa
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - difa_network

networks:
    difa_network:
        driver: bridge

volumes:
    db_data:


